import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Link2, RefreshCw, ShieldCheck } from "lucide-react";
import { Navigate } from "./router";
import { useAuth } from "./auth";
import { DashHeader, ErrorNotice, Loading, Status } from "./components";
import { supabase } from "./supabase";
import { Artist, Contract, Credit, dateBR, money, Mission, Profile, Referral, Submission } from "./stage";

type AdminSubmission=Submission&{artist_missions:Mission&{artists:Artist}};
type AuditRow={id:string;action:string;entity_type:string;reason:string|null;created_at:string};
type AdminData={artists:Artist[];contracts:Contract[];profiles:Profile[];submissions:AdminSubmission[];referrals:Referral[];credits:Credit[];missions:Mission[];audit:AuditRow[]};

export function AdminPage(){const {user,profile,loading:authLoading}=useAuth();const [data,setData]=useState<AdminData|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [tab,setTab]=useState("overview");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const [a,c,p,s,r,cr,m,au]=await Promise.all([
    supabase.from("artists").select("*").order("stage_name"),supabase.from("artist_contracts").select("*").order("created_at",{ascending:false}),supabase.from("profiles").select("*").order("created_at",{ascending:false}),supabase.from("mission_submissions").select("*, artist_missions(*, mission_templates(*), artists(*))").order("submitted_at",{ascending:false}),supabase.from("referrals").select("*").order("created_at",{ascending:false}),supabase.from("credit_ledger").select("*").order("created_at",{ascending:false}),supabase.from("artist_missions").select("*, mission_templates(*)").order("created_at"),supabase.from("audit_log").select("id,action,entity_type,reason,created_at").order("created_at",{ascending:false}).limit(50)]);for(const x of [a,c,p,s,r,cr,m,au])if(x.error)throw x.error;setData({artists:(a.data||[]) as Artist[],contracts:(c.data||[]) as Contract[],profiles:(p.data||[]) as Profile[],submissions:(s.data||[]) as unknown as AdminSubmission[],referrals:(r.data||[]) as Referral[],credits:(cr.data||[]) as Credit[],missions:(m.data||[]) as unknown as Mission[],audit:(au.data||[]) as AuditRow[]})}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar o painel.")}finally{setLoading(false)}},[]);
  useEffect(()=>{if(profile?.role==="admin")void load()},[profile,load]);if(authLoading)return <Loading/>;if(!user)return <Navigate to="/login" replace/>;if(profile?.role!=="admin"||profile.status!=="active")return <Navigate to="/portal" replace/>;if(loading&&!data)return <Loading/>;if(!data)return <div className="dashboard"><DashHeader admin/><main className="auth-wrap"><ErrorNotice>{error||"Painel indisponível."}</ErrorNotice></main></div>;
  const pending=data.submissions.filter(s=>["submitted","under_review","changes_requested"].includes(s.status));
  return <div className="dashboard"><DashHeader admin/><main className="dash-main"><div className="shell"><div className="between"><div><p className="eyebrow">Operação HAUCK Stage</p><h1 className="section-title">Painel administrativo</h1></div><button className="btn" onClick={()=>void load()}><RefreshCw size={16}/> Atualizar</button></div>{error&&<ErrorNotice>{error}</ErrorNotice>}<div className="admin-nav">{[["overview","Visão geral"],["submissions","Submissões"],["referrals","Indicações"],["users","Usuários"],["artists","Artistas"],["missions","Missões"],["audit","Auditoria"]].map(([id,label])=><button className={`tab ${tab===id?"active":""}`} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>{tab==="overview"&&<Overview data={data} pending={pending.length}/>} {tab==="submissions"&&<SubmissionQueue items={data.submissions} reload={load}/>} {tab==="referrals"&&<ReferralAdmin items={data.referrals} reload={load}/>} {tab==="users"&&<UserLink profiles={data.profiles} artists={data.artists} reload={load}/>} {tab==="artists"&&<ArtistAdmin artists={data.artists} contracts={data.contracts} credits={data.credits}/>} {tab==="missions"&&<MissionAdmin items={data.missions} artists={data.artists} reload={load}/>} {tab==="audit"&&<Audit items={data.audit}/>}</div></main></div>}

function Overview({data,pending}:{data:AdminData;pending:number}){const released=data.credits.filter(c=>c.status==="posted").reduce((n,c)=>n+c.amount_cents,0);return <section><div className="metric-grid"><Metric l="Artistas" v={String(data.artists.length)}/><Metric l="Submissões pendentes" v={String(pending)}/><Metric l="Indicações" v={String(data.referrals.length)}/><Metric l="Créditos liberados" v={money(released)}/></div><div className="grid-2"><div className="panel card"><ShieldCheck color="var(--ok)"/><h3>Validação humana ativa</h3><p className="muted">Nenhuma submissão gera crédito automaticamente. Aprovação, correção e recusa passam pela fila administrativa.</p></div><div className="panel card"><CheckCircle2 color="var(--gold)"/><h3>Proteção contra duplicidade</h3><p className="muted">As RPCs do banco impedem crédito repetido e respeitam o teto contratual.</p></div></div></section>}
function Metric({l,v}:{l:string;v:string}){return <div className="panel metric"><span className="eyebrow">{l}</span><div className="value">{v}</div></div>}

function SubmissionQueue({items,reload}:{items:AdminSubmission[];reload:()=>Promise<void>}){const [busy,setBusy]=useState("");const [error,setError]=useState("");const act=async(item:AdminSubmission,decision:"under_review"|"changes_requested"|"rejected"|"approve")=>{let review="";if(decision!=="under_review")review=window.prompt(decision==="approve"?"Observação da aprovação (opcional)":"Informe a orientação para o artista:")||"";if(["changes_requested","rejected"].includes(decision)&&!review)return;setBusy(item.id);setError("");const result=decision==="approve"?await supabase.rpc("approve_submission",{p_submission_id:item.id,p_review:review||null}):await supabase.rpc("review_submission",{p_submission_id:item.id,p_decision:decision,p_review:review});if(result.error)setError(result.error.message);else await reload();setBusy("")};return <section><p className="eyebrow">Fila de validação</p><h2 className="section-title">Submissões de missões</h2>{error&&<ErrorNotice>{error}</ErrorNotice>}<div className="mission-grid">{items.length===0?<div className="panel empty">Nenhuma submissão.</div>:items.map(s=>{const m=s.artist_missions;return <article className="panel mission" key={s.id}><div className="mission-top"><span className="tag">{m.artists.stage_name}</span><Status value={s.status}/></div><h3 style={{marginTop:16}}>{m.mission_templates.title}</h3><p className="muted">{s.artist_comment||"Sem comentário do artista."}</p><a className="btn btn-quiet" href={s.submission_url}>Abrir publicação</a><div className="actions"><button className="btn" disabled={busy===s.id} onClick={()=>void act(s,"under_review")}>Colocar em análise</button><button className="btn" disabled={busy===s.id} onClick={()=>void act(s,"changes_requested")}>Solicitar correção</button><button className="btn" disabled={busy===s.id} onClick={()=>void act(s,"rejected")}>Recusar</button><button className="btn btn-primary" disabled={busy===s.id||["approved","credited"].includes(s.status)} onClick={()=>void act(s,"approve")}>Aprovar e creditar</button></div>{s.admin_review&&<div className="notice">Última revisão: {s.admin_review}</div>}</article>})}</div></section>}

function ReferralAdmin({items,reload}:{items:Referral[];reload:()=>Promise<void>}){const [busy,setBusy]=useState("");const [error,setError]=useState("");const update=async(item:Referral,status:string)=>{setBusy(item.id);setError("");const {error:e}=await supabase.from("referrals").update({status}).eq("id",item.id);if(e)setError(e.message);else await reload();setBusy("")};const release=async(item:Referral)=>{setBusy(item.id);setError("");const reason=window.prompt("Referência do pagamento/contrato:")||"";if(!reason){setBusy("");return}const {error:e}=await supabase.rpc("release_referral_credit",{p_referral_id:item.id,p_reason:reason});if(e)setError(e.message);else await reload();setBusy("")};return <section><p className="eyebrow">Pipeline de indicações</p><h2 className="section-title">Crédito só após pagamento.</h2>{error&&<ErrorNotice>{error}</ErrorNotice>}<div className="table-wrap"><table><thead><tr><th>Indicado</th><th>Produto</th><th>Status</th><th>Previsto</th><th>Ações</th></tr></thead><tbody>{items.length===0?<tr><td colSpan={5}>Nenhuma indicação.</td></tr>:items.map(i=><tr key={i.id}><td>{i.referred_name}<br/><span className="muted">{i.referred_contact||"Sem contato"}</span></td><td>{i.product_interest}</td><td><Status value={i.status}/></td><td>{money(i.planned_credit_cents)}</td><td><div className="row"><select className="select" style={{width:190}} value={i.status} disabled={busy===i.id||i.released_credit_cents>0} onChange={e=>void update(i,e.target.value)}>{["new","contacted","qualified","proposal","paid"].map(s=><option value={s} key={s}>{s}</option>)}</select><button className="btn btn-primary" disabled={busy===i.id||i.status!=="paid"||i.released_credit_cents>0} onClick={()=>void release(i)}>Liberar crédito</button></div></td></tr>)}</tbody></table></div></section>}

function UserLink({profiles,artists,reload}:{profiles:Profile[];artists:Artist[];reload:()=>Promise<void>}){const [userId,setUserId]=useState("");const [artistId,setArtistId]=useState(artists[0]?.id||"");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const pending=profiles.filter(p=>p.role!=="admin"&&(p.status==="pending"||!artists.some(a=>a.user_id===p.user_id)));const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");const {error:rpcError}=await supabase.rpc("link_artist_user",{p_user_id:userId,p_artist_id:artistId});if(rpcError)setError(rpcError.message);else{setUserId("");await reload()}setBusy(false)};return <section><p className="eyebrow">Controle de acesso</p><h2 className="section-title">Vincular usuário ao artista.</h2><div className="grid-2"><form className="panel card" onSubmit={submit}>{error&&<ErrorNotice>{error}</ErrorNotice>}<div className="field"><label htmlFor="pending-user">Usuário pendente</label><select id="pending-user" className="select" required value={userId} onChange={e=>setUserId(e.target.value)}><option value="">Selecione…</option>{pending.map(p=><option value={p.user_id} key={p.user_id}>{p.name||p.user_id}</option>)}</select></div><div className="field"><label htmlFor="link-artist">Artista</label><select id="link-artist" className="select" value={artistId} onChange={e=>setArtistId(e.target.value)}>{artists.map(a=><option value={a.id} key={a.id}>{a.stage_name} · {a.plan}</option>)}</select></div><button className="btn btn-primary" disabled={busy||!userId||!artistId}><Link2 size={16}/> Vincular e ativar</button></form><div className="panel card"><h3>Proteções</h3><ul className="list"><li>Somente o admin pode vincular.</li><li>Um usuário não pode acessar dois artistas.</li><li>Um artista não pode ter dois usuários.</li><li>A operação fica registrada na auditoria.</li></ul></div></div></section>}

function ArtistAdmin({artists,contracts,credits}:{artists:Artist[];contracts:Contract[];credits:Credit[]}){return <section><p className="eyebrow">Contratos</p><h2 className="section-title">Artistas e Road to Zero.</h2><div className="mission-grid">{artists.map(a=>{const c=contracts.find(x=>x.artist_id===a.id);const total=credits.filter(x=>x.artist_id===a.id&&x.status==="posted").reduce((n,x)=>n+x.amount_cents,0);return <article className="panel mission" key={a.id}><div className="mission-top"><span className="tag">{a.plan}</span><Status value={a.status}/></div><h3 style={{marginTop:16}}>{a.stage_name}</h3><p className="muted">Usuário: {a.user_id?"Vinculado":"Aguardando vínculo"}</p>{c&&<><div className="progress"><span style={{width:`${Math.min(100,total/c.first_year_target_cents*100)}%`}}/></div><ul className="list small"><li>Condição: {money(c.special_setup_cents)} + {money(c.monthly_care_cents)}/mês</li><li>Primeiro ano: {money(c.first_year_target_cents)}</li><li>Créditos: {money(total)}</li></ul></>}</article>})}</div></section>}

function MissionAdmin({items,artists,reload}:{items:Mission[];artists:Artist[];reload:()=>Promise<void>}){const [busy,setBusy]=useState("");const [error,setError]=useState("");const save=async(m:Mission,form:HTMLFormElement)=>{const fd=new FormData(form);setBusy(m.id);setError("");const patch={status:String(fd.get("status")),due_at:fd.get("due_at")?new Date(String(fd.get("due_at"))).toISOString():null,planned_credit_cents:Math.round(Number(fd.get("credit"))*100)};const {error:e}=await supabase.from("artist_missions").update(patch).eq("id",m.id);if(e)setError(e.message);else await reload();setBusy("")};return <section><p className="eyebrow">Operação</p><h2 className="section-title">Atribuições de missões.</h2>{error&&<ErrorNotice>{error}</ErrorNotice>}<div className="mission-grid">{items.map(m=><form className="panel mission" key={m.id} onSubmit={e=>{e.preventDefault();void save(m,e.currentTarget)}}><span className="tag">{artists.find(a=>a.id===m.artist_id)?.stage_name||"Artista"}</span><h3 style={{marginTop:16}}>{m.mission_templates.title}</h3><div className="field"><label>Status</label><select className="select" name="status" defaultValue={m.status}>{["available","in_progress","submitted","under_review","changes_requested","rejected","approved","credited"].map(s=><option key={s}>{s}</option>)}</select></div><div className="field"><label>Prazo</label><input className="input" type="date" name="due_at" defaultValue={m.due_at?.slice(0,10)||""}/></div><div className="field"><label>Crédito planejado (R$)</label><input className="input" type="number" min="0" step="1" name="credit" defaultValue={m.planned_credit_cents/100} disabled={["approved","credited"].includes(m.status)}/></div><button className="btn" disabled={busy===m.id}>Salvar atribuição</button></form>)}</div></section>}

function Audit({items}:{items:AuditRow[]}){return <section><p className="eyebrow">Auditoria</p><h2 className="section-title">Últimas operações.</h2><div className="table-wrap"><table><thead><tr><th>Data</th><th>Ação</th><th>Entidade</th><th>Motivo</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{dateBR(i.created_at)}</td><td>{i.action}</td><td>{i.entity_type}</td><td>{i.reason||"—"}</td></tr>)}</tbody></table></div></section>}
