import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Copy, ExternalLink, Flag, Gift, Send, Sparkles } from "lucide-react";
import { Navigate } from "./router";
import { useAuth } from "./auth";
import { DashHeader, ErrorNotice, Loading, Status } from "./components";
import { supabase } from "./supabase";
import { Artist, Contract, Credit, dateBR, DIH, money, Mission, Referral, RoadSummary, STATUS_LABELS, Submission } from "./stage";

type PortalData = { artist: Artist; contract: Contract; missions: Mission[]; submissions: Submission[]; referrals: Referral[]; credits: Credit[]; road: RoadSummary };
const emptyRoad: RoadSummary={credits_total_cents:0,content_credits_cents:0,referral_credits_cents:0,content_cap_cents:70000,setup_target_cents:149000,six_month_target_cents:238400,first_year_target_cents:327800,remaining_setup_cents:149000,remaining_six_month_cents:238400,remaining_first_year_cents:327800,progress_first_year_percent:0};

export function PortalPage() {
  const { user, profile, loading:authLoading }=useAuth(); const [data,setData]=useState<PortalData|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [tab,setTab]=useState("road");
  const load=useCallback(async()=>{if(!user)return;setLoading(true);setError("");try{
    const {data:artist,error:aErr}=await supabase.from("artists").select("*").eq("user_id",user.id).eq("status","active").maybeSingle();if(aErr)throw aErr;if(!artist){setData(null);setLoading(false);return}
    const [contractRes,missionRes,submissionRes,referralRes,creditRes,roadRes]=await Promise.all([
      supabase.from("artist_contracts").select("*").eq("artist_id",artist.id).eq("active",true).single(),
      supabase.from("artist_missions").select("*, mission_templates(*)").eq("artist_id",artist.id).order("created_at"),
      supabase.from("mission_submissions").select("*").order("submitted_at",{ascending:false}),
      supabase.from("referrals").select("*").eq("artist_id",artist.id).order("created_at",{ascending:false}),
      supabase.from("credit_ledger").select("*").eq("artist_id",artist.id).order("created_at",{ascending:false}),
      supabase.rpc("get_road_to_zero_summary"),
    ]);if(contractRes.error)throw contractRes.error;if(missionRes.error)throw missionRes.error;if(submissionRes.error)throw submissionRes.error;if(referralRes.error)throw referralRes.error;if(creditRes.error)throw creditRes.error;if(roadRes.error)throw roadRes.error;
    setData({artist:artist as Artist,contract:contractRes.data as Contract,missions:(missionRes.data||[]) as unknown as Mission[],submissions:(submissionRes.data||[]) as Submission[],referrals:(referralRes.data||[]) as Referral[],credits:(creditRes.data||[]) as Credit[],road:(roadRes.data||emptyRoad) as RoadSummary});
  }catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar o portal.")}finally{setLoading(false)}},[user]);
  useEffect(()=>{void load()},[load]);
  if(authLoading)return <Loading/>; if(!user)return <Navigate to="/login" replace/>; if(profile?.role==="admin")return <Navigate to="/admin" replace/>; if(loading)return <Loading/>;
  if(!data)return <div className="dashboard"><DashHeader/><main className="auth-wrap"><section className="panel auth-card"><p className="eyebrow">Acesso recebido</p><h1 className="section-title">Aguardando vínculo.</h1><p className="lead">Seu login está funcionando. A HAUCK Stage ainda precisa associar este e-mail ao seu perfil de artista.</p>{error&&<ErrorNotice>{error}</ErrorNotice>}</section></main></div>;
  return <div className="dashboard"><DashHeader/><main className="dash-main"><div className="shell"><div className="between"><div><p className="eyebrow">Portal do artista</p><h1 className="section-title">{data.artist.stage_name}</h1><p className="muted">{data.artist.plan} · ciclo de {data.contract.cycle_months} meses · até {dateBR(data.artist.program_ends_at)}</p></div><a className="btn" href={`/artistas/${data.artist.slug}`}>Ver página pública <ExternalLink size={16}/></a></div>{error&&<ErrorNotice>{error}</ErrorNotice>}<div className="admin-nav">{[["road","Road to Zero"],["missions","Missões"],["lab","Content Lab"],["referrals","Indicações"],["credits","Créditos"]].map(([id,label])=><button key={id} className={`tab ${tab===id?"active":""}`} onClick={()=>setTab(id)}>{label}</button>)}</div>{tab==="road"&&<Road road={data.road}/>} {tab==="missions"&&<Missions data={data} reload={load}/>} {tab==="lab"&&<ContentLab missions={data.missions}/>} {tab==="referrals"&&<Referrals items={data.referrals} reload={load}/>} {tab==="credits"&&<Credits items={data.credits}/>}</div></main></div>;
}

function Road({road}:{road:RoadSummary}){
  const goals=[{name:"Implantação",target:road.setup_target_cents,remaining:road.remaining_setup_cents},{name:"Implantação + 6 meses",target:road.six_month_target_cents,remaining:road.remaining_six_month_cents},{name:"Primeiro ano",target:road.first_year_target_cents,remaining:road.remaining_first_year_cents}];
  return <section><div className="panel card highlight"><div className="between"><div><p className="eyebrow">Road to Zero</p><h2 className="section-title">{money(road.credits_total_cents)} conquistados</h2></div><div className="tag">{Math.min(100,Number(road.progress_first_year_percent)||0).toFixed(1)}% do primeiro ano</div></div><div className="progress"><span style={{width:`${Math.min(100,Number(road.progress_first_year_percent)||0)}%`}}/></div><div className="metric-grid"><div className="metric"><span className="muted small">Créditos liberados</span><div className="value">{money(road.credits_total_cents)}</div></div><div className="metric"><span className="muted small">Por conteúdo</span><div className="value">{money(road.content_credits_cents)}</div></div><div className="metric"><span className="muted small">Por indicações</span><div className="value">{money(road.referral_credits_cents)}</div></div><div className="metric"><span className="muted small">Teto de conteúdo</span><div className="value">{money(road.content_cap_cents)}</div></div></div></div><div className="goal-grid">{goals.map(g=>{const pct=Math.min(100,Math.max(0,(road.credits_total_cents/g.target)*100));return <article className="panel goal" key={g.name}><p className="eyebrow">{g.name}</p><h3>{money(g.target)}</h3><div className="progress"><span style={{width:`${pct}%`}}/></div><p className="small muted">{g.remaining===0?"Meta alcançada":`Faltam ${money(g.remaining)}`}</p></article>})}</div><div className="notice" style={{marginTop:18}}>Crédito planejado ou enviado não entra nesta barra. O progresso considera somente valores aprovados e lançados no histórico.</div></section>;
}

function Missions({data,reload}:{data:PortalData;reload:()=>Promise<void>}){const [selected,setSelected]=useState<Mission|null>(null);const [url,setUrl]=useState("");const [comment,setComment]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const latest=useMemo(()=>new Map(data.submissions.map(s=>[s.artist_mission_id,s])),[data.submissions]);
  const start=async(m:Mission)=>{setBusy(true);setError("");const {error:e}=await supabase.rpc("start_mission",{p_artist_mission_id:m.id});if(e)setError(e.message);else await reload();setBusy(false)};
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!selected)return;setBusy(true);setError("");const {error:rpcError}=await supabase.rpc("submit_mission",{p_artist_mission_id:selected.id,p_url:url,p_comment:comment||null});if(rpcError)setError(rpcError.message);else{setSelected(null);setUrl("");setComment("");await reload()}setBusy(false)};
  return <section><div className="between"><div><p className="eyebrow">Stage Missions</p><h2 className="section-title">Missões disponíveis</h2></div><span className="tag">{data.missions.length} missões</span></div>{error&&<ErrorNotice>{error}</ErrorNotice>}<div className="mission-grid">{data.missions.map(m=>{const t=m.mission_templates;const sub=latest.get(m.id);return <article className="panel mission" key={m.id}><div className="mission-top"><span className="tag">{t.category}</span><Status value={m.status}/></div><h3 style={{marginTop:16}}>{t.title}</h3><p className="muted">{t.objective}</p><ul className="list small"><li>{t.platform||"HAUCK Stage"} · {t.format||"Formato definido no briefing"}</li><li>{money(m.planned_credit_cents)} planejados</li><li>Permanência mínima: {t.minimum_online_days} dias</li><li>Prazo: {dateBR(m.due_at)}</li></ul>{sub?.admin_review&&<div className="notice">Revisão: {sub.admin_review}</div>}<div className="actions">{["available","changes_requested","rejected"].includes(m.status)&&<button className="btn" disabled={busy} onClick={()=>void start(m)}>Começar missão</button>}{["in_progress","changes_requested","rejected"].includes(m.status)&&<button className="btn btn-primary" onClick={()=>setSelected(m)}>Enviar para validação <Send size={15}/></button>}{sub&&<a className="btn btn-quiet" href={sub.submission_url}>Ver envio</a>}</div></article>})}</div>{selected&&<div className="panel card highlight" style={{marginTop:18}}><div className="between"><div><p className="eyebrow">Enviar para validação</p><h3>{selected.mission_templates.title}</h3></div><button className="btn" onClick={()=>setSelected(null)}>Fechar</button></div><form onSubmit={submit}><div className="field"><label htmlFor="mission-url">Link público da publicação</label><input id="mission-url" className="input" type="url" required pattern="https?://.*" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..."/></div><div className="field"><label htmlFor="mission-comment">Observação opcional</label><textarea id="mission-comment" className="textarea" value={comment} onChange={e=>setComment(e.target.value)}/></div><button className="btn btn-primary" disabled={busy}>{busy?"Enviando…":"Enviar para revisão"}</button></form></div>}</section>}

function ContentLab({missions}:{missions:Mission[]}){const [copied,setCopied]=useState("");const complete=(m:Mission)=>`Atue como estrategista de conteúdo especializado em DJs e produtores musicais.\n\nArtista: ${DIH.name}\nPlataforma: ${m.mission_templates.platform||"Definir"}\nFormato: ${m.mission_templates.format||"Definir"}\nObjetivo: ${m.mission_templates.objective}\nRequisitos: ${(m.mission_templates.requirements||[]).join("; ")||m.mission_templates.instructions}\n\n${m.mission_templates.prompt_template}\n\nNão invente apresentações, números, lançamentos, selos, resultados ou conquistas. Use somente informações confirmadas pelo artista.`;const copy=async(m:Mission)=>{await navigator.clipboard.writeText(complete(m));setCopied(m.id);setTimeout(()=>setCopied(""),1800)};return <section><p className="eyebrow">Content Lab</p><h2 className="section-title">Um prompt pronto por missão.</h2><p className="lead">Copie e use no ChatGPT, Claude, Gemini ou outra IA. O prompt já preserva a regra de não inventar informações.</p><div className="mission-grid">{missions.map(m=><article className="panel mission" key={m.id}><div className="mission-top"><span className="tag">{m.mission_templates.category}</span><Sparkles size={18} color="var(--ember)"/></div><h3 style={{marginTop:16}}>{m.mission_templates.title}</h3><pre className="prompt">{complete(m)}</pre><button className="btn btn-primary" onClick={()=>void copy(m)}><Copy size={16}/> {copied===m.id?"Copiado":"Copiar prompt"}</button></article>)}</div></section>}

function Referrals({items,reload}:{items:Referral[];reload:()=>Promise<void>}){const [name,setName]=useState("");const [contact,setContact]=useState("");const [product,setProduct]=useState("Mainstage");const [notes,setNotes]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");const {error:rpcError}=await supabase.rpc("create_referral",{p_referred_name:name,p_referred_contact:contact||null,p_product_interest:product,p_artist_notes:notes||null});if(rpcError)setError(rpcError.message);else{setName("");setContact("");setNotes("");await reload()}setBusy(false)};return <section><p className="eyebrow">Indicações</p><h2 className="section-title">Conexões que podem virar crédito.</h2><div className="grid-2"><form className="panel card" onSubmit={submit}><h3>Registrar indicação</h3>{error&&<ErrorNotice>{error}</ErrorNotice>}<div className="field"><label htmlFor="ref-name">Nome</label><input id="ref-name" className="input" required value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label htmlFor="ref-contact">Contato opcional</label><input id="ref-contact" className="input" value={contact} onChange={e=>setContact(e.target.value)}/></div><div className="field"><label htmlFor="ref-product">Interesse</label><select id="ref-product" className="select" value={product} onChange={e=>setProduct(e.target.value)}>{["Warm-Up","Mainstage","Stage Catalog","Headliner App"].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label htmlFor="ref-notes">Contexto opcional</label><textarea id="ref-notes" className="textarea" value={notes} onChange={e=>setNotes(e.target.value)}/></div><button className="btn btn-primary" disabled={busy}><Flag size={16}/> {busy?"Registrando…":"Registrar indicação"}</button></form><div className="panel card"><h3>Regras essenciais</h3><ul className="list"><li>Crédito previsto não é crédito liberado.</li><li>A contratação e o pagamento precisam ser confirmados.</li><li>O valor nunca é convertido em dinheiro.</li><li>A validação permanece manual.</li></ul></div></div><div className="table-wrap" style={{marginTop:18}}><table><thead><tr><th>Indicação</th><th>Produto</th><th>Status</th><th>Previsto</th><th>Liberado</th></tr></thead><tbody>{items.length===0?<tr><td colSpan={5}>Nenhuma indicação registrada.</td></tr>:items.map(x=><tr key={x.id}><td>{x.referred_name}</td><td>{x.product_interest}</td><td><Status value={STATUS_LABELS[x.status]||x.status}/></td><td>{money(x.planned_credit_cents)}</td><td>{money(x.released_credit_cents)}</td></tr>)}</tbody></table></div></section>}

function Credits({items}:{items:Credit[]}){return <section><p className="eyebrow">Stage Credits</p><h2 className="section-title">Histórico auditável.</h2><div className="table-wrap"><table><thead><tr><th>Data</th><th>Origem</th><th>Descrição</th><th>Status</th><th>Valor</th></tr></thead><tbody>{items.length===0?<tr><td colSpan={5}>Ainda não há créditos liberados.</td></tr>:items.map(c=><tr key={c.id}><td>{dateBR(c.created_at)}</td><td>{c.source_type}</td><td>{c.description}</td><td><Status value={c.status}/></td><td><strong>{money(c.amount_cents)}</strong></td></tr>)}</tbody></table></div><div className="notice" style={{marginTop:18}}><Gift size={15}/> O histórico mostra apenas lançamentos efetivos. Envios aguardando análise aparecem na área Missões.</div></section>}
