import { useState } from "react";
import { Link } from "./router";
import { ArrowRight, Building2, Check, Headphones, LockKeyhole, Sparkles } from "lucide-react";
import { DIH, PRICES, whatsapp } from "./stage";
import { Footer, PublicHeader } from "./components";

const individual: Array<{ name: string; who: string; setup: string; monthly: string; items: string[]; featured?: boolean }> = [
  { name: "Warm-Up", who: "Para sair do improviso com uma presença profissional.", ...PRICES.individual.warmup, items: ["Página premium", "Bio e links", "Player", "Booking direto"] },
  { name: "Mainstage", who: "Para artistas ativos com conteúdo, lançamentos e agenda.", ...PRICES.individual.mainstage, items: ["Tudo do Warm-Up", "Conteúdos e lançamentos", "Press kit", "Conversão ampliada"], featured: true },
  { name: "Headliner App", who: "Para uma experiência própria, avançada e sob medida.", ...PRICES.individual.headliner, items: ["Experiência app-like", "Automações", "Analytics", "Arquitetura exclusiva"] },
];

export function Home() {
  return <><PublicHeader/><main><section className="hero"><div className="shell hero-grid"><div><p className="eyebrow">Presença digital para DJs e produtores</p><h1>Seu som merece uma <span className="accent">presença de headliner.</span></h1><p className="lead">Uma casa digital para música, booking, press kit e autoridade — construída para o momento real da sua carreira.</p><div className="actions"><a className="btn btn-primary" href="#planos">Escolher meu palco <ArrowRight size={18}/></a><Link className="btn" to="/artistas/dih-ribeiro">Ver artista Mainstage</Link></div></div><div className="panel art-card"><span className="eyebrow">HAUCK Stage</span><div className="name">Música.<br/><span className="accent">Imagem.</span><br/>Booking.</div><div className="wave">{[25,55,38,88,52,70,31,96,45,78,28,63,44].map((h,i)=><span key={i} style={{height:`${h}%`}}/>)}</div></div></div></section><section className="section" id="planos"><div className="shell"><p className="eyebrow">Produtos oficiais</p><h2 className="section-title">Escolha o tamanho do seu palco.</h2><div className="grid-3">{individual.map(p=><article className={`panel card ${p.featured?"highlight":""}`} key={p.name}>{p.featured&&<span className="tag">Mais recomendado</span>}<h3>{p.name}</h3><p className="muted">{p.who}</p><div className="price">{p.setup}</div><div className="muted">+ {p.monthly}</div><ul className="list">{p.items.map(i=><li key={i}>{i}</li>)}</ul><a className="btn btn-primary" href={whatsapp(`Olá, quero conhecer o ${p.name} da HAUCK Stage.`)}>Conhecer {p.name}</a></article>)}</div></div></section><section className="section"><div className="shell grid-2"><Link className="panel card highlight" to="/partner"><Sparkles color="var(--ember)"/><h2 className="section-title">Stage Partner</h2><p className="lead">Missões, conteúdo e indicações transformados em Stage Credits dentro de regras transparentes.</p><span className="btn">Conhecer o programa</span></Link><Link className="panel card" to="/agencias"><Building2 color="var(--gold)"/><h2 className="section-title">Stage Catalog</h2><p className="lead">Casting organizado, páginas individuais e booking centralizado para agências.</p><span className="btn">Ver solução B2B</span></Link></div></section></main><Footer/></>;
}

const contentTabs = ["Sets","Produções / Lançamentos","Vídeos","Agenda"];
export function DihPage() {
  const [tab,setTab]=useState(contentTabs[0]);
  return <><PublicHeader/><main><section className="hero"><div className="shell hero-grid"><div><p className="eyebrow">{DIH.category}</p><h1>DIH <span className="accent">RIBEIRO</span></h1><p className="lead">Uma página Mainstage em preparação para reunir apresentação, conteúdos, press kit e booking em um só endereço.</p><div className="actions"><a className="btn btn-primary" href={DIH.soundcloud}>Ouvir no SoundCloud <Headphones size={18}/></a><a className="btn" href="#booking">Booking</a></div></div><div className="panel art-card"><span className="eyebrow">DJ & Producer</span><div className="name">DIH<br/><span className="accent">RIBEIRO</span></div><p className="muted">Composição provisória — pronta para receber a identidade e as fotos validadas pelo artista.</p></div></div></section><section className="section"><div className="shell grid-2"><div><p className="eyebrow">Sobre</p><h2 className="section-title">Biografia em preparação.</h2><p className="lead">O texto definitivo será construído no onboarding com as informações validadas pelo artista. Nenhuma trajetória, apresentação ou conquista será presumida.</p></div><div className="panel card"><p className="eyebrow">Identidade musical</p><h3>Curadoria pendente</h3><p className="muted">Estilos, referências e direção sonora serão publicados após validação do Dih.</p></div></div></section><section className="section" id="conteudos"><div className="shell"><p className="eyebrow">Conteúdos</p><h2 className="section-title">O centro vivo da Mainstage.</h2><div className="tabs">{contentTabs.map(t=><button className={`tab ${tab===t?"active":""}`} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="panel empty"><h3>{tab}</h3><p className="muted">Conteúdo em organização. Os materiais confirmados serão publicados aqui.</p>{tab==="Sets"&&<a className="btn btn-primary" href={DIH.soundcloud}>Abrir SoundCloud oficial</a>}</div></div></section><section className="section" id="booking"><div className="shell panel card highlight"><p className="eyebrow">Booking</p><h2 className="section-title">Consulte disponibilidade.</h2><p className="lead">O canal definitivo de booking será ativado após validação do artista.</p><a className="btn btn-primary" href={whatsapp("Olá, quero informações de booking do Dih Ribeiro.")}>Solicitar informações</a></div></section></main><Footer/></>;
}

export function PartnerPage() {
  const steps=["O artista recebe missões objetivas e prompts prontos.","Publica e envia o link para validação.","A HAUCK Stage revisa requisitos e permanência.","Créditos aprovados entram no Road to Zero."];
  return <><PublicHeader/><main><section className="hero"><div className="shell"><p className="eyebrow">HAUCK Stage Partner</p><h1>PARTICIPAÇÃO QUE VIRA <span className="accent">CRÉDITO.</span></h1><p className="lead">Uma trilha privada para artistas-case transformarem conteúdo validado e indicações convertidas em Stage Credits.</p><div className="actions"><Link className="btn btn-primary" to="/login">Acessar meu portal <LockKeyhole size={18}/></Link></div></div></section><section className="section"><div className="shell"><p className="eyebrow">Como funciona</p><h2 className="section-title">Transparente do início ao crédito.</h2><div className="grid-2">{steps.map((s,i)=><div className="panel card" key={s}><span className="tag">0{i+1}</span><h3>{s}</h3></div>)}</div></div></section><section className="section"><div className="shell grid-3">{[{t:"Missões",d:"Briefing, formato, requisitos, prazo e crédito planejado."},{t:"Content Lab",d:"Prompt pronto para criar conteúdo em qualquer IA, sem inventar fatos."},{t:"Road to Zero",d:"Progresso real, separando crédito previsto, pendente e liberado."}].map(x=><article className="panel card" key={x.t}><Sparkles color="var(--ember)"/><h3>{x.t}</h3><p className="muted">{x.d}</p></article>)}</div></section></main><Footer/></>;
}

export function AgenciesPage() {
  const plans=[{n:"Warm-Up",...PRICES.catalog.warmup},{n:"Mainstage",...PRICES.catalog.mainstage},{n:"Headliner App",...PRICES.catalog.headliner}];
  return <><PublicHeader/><main><section className="hero"><div className="shell"><p className="eyebrow">HAUCK Stage Catalog</p><h1>SEU CASTING EM UM <span className="accent">CATÁLOGO PREMIUM.</span></h1><p className="lead">Hub central, páginas individuais, materiais organizados e booking direto — com 0% de comissão sobre cachês.</p><div className="actions"><a className="btn btn-primary" href={whatsapp("Olá, represento uma agência e quero conhecer o HAUCK Stage Catalog.")}>Agendar diagnóstico</a></div></div></section><section className="section"><div className="shell"><div className="panel card highlight"><p className="eyebrow">Estrutura central</p><div className="price">{PRICES.catalog.hub.setup}</div><p className="lead">+ {PRICES.catalog.hub.monthly} de cuidado mensal · entrada mínima recomendada de 3 artistas.</p></div><h2 className="section-title">Valores por artista no catálogo.</h2><div className="grid-3">{plans.map(p=><div className="panel card" key={p.n}><h3>{p.n}</h3><div className="price">{p.setup}</div><p className="muted">+ {p.monthly}</p><ul className="list"><li>Página individual</li><li>Booking pela agência</li><li>Manutenção definida em escopo</li></ul></div>)}</div></div></section><section className="section"><div className="shell grid-2"><div className="panel card"><h3>Co-branded</h3><p className="muted">Identidade da agência com assinatura discreta “Powered by HAUCK Stage”.</p></div><div className="panel card"><h3>White-label</h3><p className="muted">Operação técnica nos bastidores, mediante escopo e condição comercial próprios.</p></div></div></section></main><Footer/></>;
}
